#!/usr/bin/env python3
"""Package submission.py into submission.zip with a chosen strategy baked in.

Reads strategies/<NAME>.json, generates the Python Strategy(...) expression,
replaces the block between BUILD_INJECT markers in submission.py, and zips
the result. The working-tree submission.py is left unchanged.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import sys
import tempfile
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SUBMISSION_PY = HERE / "submission.py"

sys.path.insert(0, str(HERE))
import strategies  # noqa: E402

INJECT_RE = re.compile(
    r'(# === BUILD_INJECT_BELOW ===\n)(.*?)(# === BUILD_INJECT_ABOVE ===)',
    re.DOTALL,
)


def make_inject_block(spec: dict) -> str:
    """The body that goes between the BUILD_INJECT markers (markers exclusive)."""
    code = strategies.codegen_strategy(spec)
    return (
        f"# Generated by build.py: pinned strategy {spec['name']!r}\n"
        f"_active_strategy: Strategy = {code}\n"
    )


def rewrite(src: str, spec: dict) -> str:
    matches = INJECT_RE.findall(src)
    if len(matches) != 1:
        raise SystemExit(
            f"ERROR: expected exactly 1 BUILD_INJECT block, found {len(matches)}"
        )
    block = make_inject_block(spec)
    return INJECT_RE.sub(
        lambda m: f"{m.group(1)}{block}{m.group(3)}",
        src,
        count=1,
    )


def smoke_test(submission_path: Path, expected_name: str) -> None:
    """Import the rewritten module in-process and run a tiny rebalance call."""
    spec = importlib.util.spec_from_file_location("_build_check", submission_path)
    if spec is None or spec.loader is None:
        raise SystemExit("ERROR: could not load module spec for smoke test")
    mod = importlib.util.module_from_spec(spec)
    sys.modules["_build_check"] = mod
    try:
        spec.loader.exec_module(mod)
    finally:
        sys.modules.pop("_build_check", None)

    got = mod.get_strategy().name
    if got != expected_name:
        raise SystemExit(
            f"ERROR: smoke test: expected strategy {expected_name!r}, got {got!r}"
        )
    import numpy as np
    hot = np.random.randint(0, 1000, size=(64, 94, 128)).astype(np.int64)
    change, _, dep, _ = mod.rebalance(hot, 32, 32)
    if dep.shape != (94, 32, 5):
        raise SystemExit(f"ERROR: smoke test: bad deployment shape {dep.shape}")
    if not isinstance(change, bool):
        raise SystemExit("ERROR: smoke test: change is not bool")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--strategy", help="name (filename stem) under strategies/")
    p.add_argument("-o", "--output", type=Path,
                   default=Path("submission.zip"))
    p.add_argument("--list", action="store_true",
                   help="List available strategy names and exit.")
    args = p.parse_args()

    available = strategies.list_strategies()
    if args.list:
        for name in available:
            print(name)
        return
    if not args.strategy:
        sys.exit(f"--strategy is required. Available: {available}")
    if args.strategy not in available:
        sys.exit(f"unknown strategy {args.strategy!r}. Available: {available}")

    spec = strategies.load_spec(args.strategy)
    src = SUBMISSION_PY.read_text()
    rewritten = rewrite(src, spec)

    with tempfile.TemporaryDirectory() as td:
        staged = Path(td) / "submission.py"
        staged.write_text(rewritten)

        smoke_test(staged, spec["name"])
        print(f"  ✓ Rewrote _active_strategy from strategies/{args.strategy}.json")
        print(f"  ✓ Smoke test: rebalance() returns valid shapes")

        args.output = args.output.resolve()
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(args.output, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            zf.write(staged, arcname="submission.py")

    size_kb = args.output.stat().st_size / 1024
    print(f"  ✓ Wrote {args.output}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
